### ISSUE TITLE
Search from results page 

### ISSUE THREAD

**Issue by mozgit** [fstate/fstate#3]
When I try to do search from result page, something goes wrong. Need to fix this.

**Comment by bth5032** [comment]
The issue here is the way we're doing searches. We basically added to every page an invisible table that can hold the search results, then on a search we just grab data using JQuery/AJAX, make the table visible, and fill it in. I think we should redirect the user to another page when they search, that would fix the problem. I didn't make this change before because I was unsure whether there was some rationale I didn't understand about doing it the other way.

**Comment by mozgit** [comment]
Fixed JS. However separate page for search results is still good idea
